parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  pool:
    name: DAS - Continuous Integration
    demands: LATEST_DOTNET_VERSION -equals 3.1
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      SonarCloudProjectKey: SkillsFundingAgency_das-notifications
      ContinueOnVulnerablePackageScanError: true

  - task: DotNetCoreCLI@2
    displayName: Publish - dotnet publish ${{ parameters.SolutionBaseName }}.Api
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/${{ parameters.SolutionBaseName }}.Api/${{ parameters.SolutionBaseName }}.Api.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c ${{ parameters.BuildConfiguration }} --no-restore --no-build

  - task: DotNetCoreCLI@2
    displayName: Publish - dotnet publish ${{ parameters.SolutionBaseName }}.MessageHandlers
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/${{ parameters.SolutionBaseName }}.MessageHandlers/${{ parameters.SolutionBaseName }}.MessageHandlers.csproj
      arguments: "--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish/${{ parameters.SolutionBaseName }}.MessageHandlers/App_Data/jobs/continuous/Notifications-MessageHandlers --no-restore --no-build"
      modifyOutputPath: false
      zipAfterPublish: false

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: pack
      packagesToPack: >
        src/SFA.DAS.Notifications.Messages/SFA.DAS.Notifications.Messages.csproj
      packDirectory: "$(build.artifactstagingdirectory)/publish"
      versioningScheme: byBuildNumber
      buildProperties: 'Version="$(Build.BuildNumber)"'

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact ${{ parameters.SolutionBaseName }}
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
